export const CHANGE_FOCUS_PLACE = "CHANGE_FOCUS_PLACE"
export const CHANGE_MAP_OPTIONS = "CHANGE_MAP_OPTIONS"
export const LOAD_PINNED_PLACES = "LOAD_PINNED_PLACES"
export const ADD_NEW_PLACE = "ADD_NEW_PLACE"
